dist: trusty
language: php
php:
  - 5.5
  - 5.6
  - 7.0
  - 7.1
  - 7.2
  - 7.3

matrix:
  fast_finish: true
  allow_failures:
    - php: 5.5
    - php: 5.6

install:
  - composer install
script:
  - vendor/bin/phpunit
